[package]
id = "docpkg"
name = "Documentation Packager"
files = [
  "README.md",
  "table/compliance.csv",
  "notes/evergreen/How to track compliance?.md",
]

[[release]]
id = "v1"

[[release]]
id = "v2"

[[standard]]
id = "SemVer 2.0.0"

[standard.last_audit]
date = "2023-01-14"
report = "about:blank"
adequate = false

[[standard.requirement]]
id = "1"

[[standard.requirement.since.v1.control]]
doc = "README.md"
annotation = "See CLI definition"

[[standard.requirement.since.v1.control.demo]]
person = [ "Sander" ]
thing = [ "CLI" ]
instruction = [ "Show that this indeed covers all interface" ]

[[standard.requirement.since.v1.control]]
code = "src/main.rs"

# Example
[standard.requirement.since.v2.out]

[[standard.requirement]]
id = "2"

[[standard.requirement.since.v1.control]]
code = "Cargo.toml"

[[standard]]
title = "Conventional Commits 1.0.0"
uri = "https://www.conventionalcommits.org/en/v1.0.0/"

[[standard.requirement]]
id = "1"
annotation = "Keeping merge commits out of scope."

[[standard.requirement]]
id = "2"
