name: Check dependency updates
on:
  schedule:
    - cron: "0 0 * * *" # every day at 00:00
  workflow_dispatch:
permissions:
  contents: read
jobs:
  scala-steward:
    runs-on: ubuntu-latest
    steps:
      - uses: scala-steward-org/scala-steward-action@f8badbe3d660cf890a08da7ea2cd4f5550c7084f # ratchet:scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.REPO_GITHUB_TOKEN }}
        env:
          PACKAGE_GITHUB_TOKEN: ${{ secrets.PACKAGE_GITHUB_TOKEN }}
