name: Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: VirtusLab/scala-cli-setup@313e80b1b8fec6ecb9c058aad0b9f02b4410caa7 # ratchet:VirtusLab/scala-cli-setup@main
        with:
          jvm: temurin:1.17.0.3
          apps: scala-cli
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # ratchet:actions/checkout@v3
      - run: scala-cli fmt --check src/main acceptance
      - run: scala-cli test src/main acceptance
