name: Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  check-workflow-pinning:
    runs-on: ubuntu-latest
    steps:
      - uses: coursier/cache-action@288585e12960315492c10d496fafb65b57d9a89b # ratchet:coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@a173ac6b0b5252a6cf506cfafdd304066bf09da8 # ratchet:VirtusLab/scala-cli-setup@main
        with:
          jvm: temurin:1.17.0.3
          apps: scala-cli
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # ratchet:actions/checkout@v3
      - run: scala-cli scripts/install-ratchet.sc
      - run: scala-cli scripts/check-workflow-dependencies.sc
  check-formatting-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: coursier/cache-action@288585e12960315492c10d496fafb65b57d9a89b # ratchet:coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@a173ac6b0b5252a6cf506cfafdd304066bf09da8 # ratchet:VirtusLab/scala-cli-setup@main
        with:
          jvm: temurin:1.17.0.3
          apps: scala-cli
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # ratchet:actions/checkout@v3
      - run: scala-cli fmt --check .
      - run: scala-cli test .
        env:
          ATLASSIAN_API_TOKEN: ${{ secrets.ATLASSIAN_API_TOKEN }}
