name: Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  check-workflow-pinning:
    runs-on: ubuntu-latest
    steps:
      - uses: coursier/cache-action@0cdf229a86211e64f9a576ee6c00cdf662f2554d # ratchet:coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@0dab3c3ec860f0443d4d25a56a549f9f46204389 # ratchet:VirtusLab/scala-cli-setup@main
        with:
          jvm: temurin:1.17.0.3
          apps: scala-cli
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # ratchet:actions/checkout@v3
      - run: scala-cli scripts/install-ratchet.sc
      - run: scala-cli scripts/check-workflow-dependencies.sc
  check-formatting-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: coursier/cache-action@0cdf229a86211e64f9a576ee6c00cdf662f2554d # ratchet:coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@0dab3c3ec860f0443d4d25a56a549f9f46204389 # ratchet:VirtusLab/scala-cli-setup@main
        with:
          jvm: temurin:1.17.0.3
          apps: scala-cli
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # ratchet:actions/checkout@v3
      - run: scala-cli fmt --check .
      - run: scala-cli test .
        env:
          ATLASSIAN_API_TOKEN: ${{ secrets.ATLASSIAN_API_TOKEN }}
