name: Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  check-workflow-pinning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # ratchet:actions/checkout@v3
      - uses: "docker://ghcr.io/sethvargo/ratchet@sha256:b3e3e8da9f6269e52a48dc45bbe7bc4801d434a0bd987aa394f9bcb99a399d61" # ratchet:docker://ghcr.io/sethvargo/ratchet:0.2.3
        with:
          args: "check .github/workflows/integration.yml"
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # ratchet:actions/checkout@v3
      - uses: coursier/cache-action@288585e12960315492c10d496fafb65b57d9a89b # ratchet:coursier/cache-action@v6.3
      - uses: VirtusLab/scala-cli-setup@06d19f37f67791511cd581eab50bc7c63b60cb37 # ratchet:VirtusLab/scala-cli-setup@v0.1
      - uses: actions/setup-java@d854b6da19cdadd9a010605529e522c2393ebd38 # ratchet:actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "19"
          cache: maven
      - run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      #- run: mvn --batch-mode deploy
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: mvn package
      - run: scala-cli run scripts/package.sc
