name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 17.x
      uses: actions/setup-node@v2
      with:
        node-version: 17.x
        cache: 'npm'
    - run: npm install
    - run: ./node_modules/.bin/cucumber-js --format=message:out.json
    - run: node parse.js > in.tex
    - run: sudo apt install -y texlive-luatex texlive-latex-base
    - run: lualatex in
    - uses: actions/upload-artifact@v3
      with:
        name: package
        path: in.pdf
