name: Package docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CLOJURE_VERSION: 1.10.3.1087

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 17.x
      uses: actions/setup-node@v2
      with:
        node-version: 17.x
        cache: 'npm'
    - run: npm install
    - run: mkdir -p out
    - run: npx cucumber-js --format=message:out/cucumber-output --format=message:out/features.html
    - run: sudo apt install -y texlive-luatex texlive-latex-base texlive-latex-recommended texlive-latex-extra preview-latex-style fonts-ibm-plex inkscape
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11
    - name: Cache Clojure install
      id: cache-clojure
      uses: actions/cache@v2
      with:
        path: ~/bin/clojure
        key: ${{ env.CLOJURE_VERSION }}
    - name: Set up Clojure
      if: steps.cache-clojure.outputs.cache-hit != 'true'
      run: |
        curl -O https://download.clojure.org/install/linux-install-${CLOJURE_VERSION}.sh
        chmod +x linux-install-${CLOJURE_VERSION}.sh
        sudo ./linux-install-${CLOJURE_VERSION}.sh --prefix ~/bin/clojure
    - name: Add Clojure to path
      run: echo "$HOME/bin/clojure/bin" >> $GITHUB_PATH
    - name: Cache maven artifacts
      id: cache-maven
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-${{ hashFiles('deps.edn') }}
    - name: Download dependencies
      if: steps.cache-maven.outputs.cache-hit != 'true'
      run: clojure -A:test -Stree
    - run: sudo apt install pandoc
    - run: clojure -X:main
    - run: mkdir pages && mv out.pdf pages/docpkg-main.pdf
    - uses: actions/upload-artifact@v3
      with:
        name: package
        path: pages/docpkg-main.pdf
    - uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: public
